### PR TITLE
Bloodmarks on bodies

### PR DESCRIPTION
**Pull request by BeefDiaper**
Includes FSkinned.cpp improvement (more detail on skinned mesh's)
(Swartz here - using another account)

### CODE REVIEW

**Comment by BeefDiaper** [comment]
Told ya I'm a sloppy programmer :P  It looked ok in WinMerge, then got butchered.

**Review by Im-dex — CHANGES_REQUESTED** [review]
Thanks for contribution, but I can't accept this PR because it contains many meaningless changes that just break code formatting. Please, use clang-format with config from 'code' folder before PRs submission.

**Comment by ghost** [comment]
I completely understand. I'll google how to use that file and then resubmit.

**Comment by ghost** [comment]
Hi again, I can't figure out how to do this. I suck at using git and related things. Feel free to close this pull request until I grow a brain.

**Comment by Im-dex** [comment]
@Swartz27 You could use ClangFormat MSVS extension for that purpose. Also, Resharper C++ can find out formatting config automagically and apply it to own formatting settings.

**Comment by ghost** [comment]
@Im-dex Can you please delete this PR? I'm going to do it over again from this account and do it properly.

**Pull request closed without merging**
